runner:
  experiment_name: toto_velocity
  save_interval: 200
  num_steps_per_env: 24
  max_iterations: 10000
  resume: false
  load_run: .*
  load_checkpoint: model_.*.pt

actor:
  hidden_dims: [512, 256, 128]
  activation: elu
  obs_normalization: true
  distribution_cfg:
    class_name: GaussianDistribution
    init_std: 1.0
    std_type: scalar

critic:
  hidden_dims: [512, 256, 128]
  activation: elu
  obs_normalization: true

algorithm:
  value_loss_coef: 1.0
  use_clipped_value_loss: true
  clip_param: 0.2
  entropy_coef: 0.01
  num_learning_epochs: 5
  num_mini_batches: 4
  learning_rate: 1.0e-3
  schedule: adaptive
  gamma: 0.99
  lam: 0.95
  desired_kl: 0.01
  max_grad_norm: 1.0
